server:
  port: 9090

spring:
  application.name: issue-light-tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/ilt_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: igathlete.ilt.model